### ISSUE TITLE
Unable to import when vocabulary or policy is already existent

### ISSUE THREAD

**Issue by kianting** [jixer/biztalk-rules-export#1]
Returns the following error:- 

Unhandled Exception: Microsoft.RuleEngine.RuleStoreRuleSetDeployedException: Rul
eset "[][]", version 1.4 has already been deployed, and canno
t be deleted.
   at Microsoft.RuleEngine.SqlRuleStore.RemoveFromDB(SqlConnection connection, R
uleSetInfo ruleSet, SqlTransaction tx)
   at Microsoft.RuleEngine.SqlRuleStore.Remove(RuleSetInfo ruleSet)
   at Microsoft.RuleEngine.RuleStore.Remove(RuleSet ruleSet)
   at BizTalkRulesUtility.Program.CopyPolicies(RuleStore sourceRuleStore, RuleSt
ore targetRuleStore) in C:\data\biztalk-rules-export-master\SOURCE\MAIN\BizTalkR
ulesUtility\Program.cs:line 70
   at BizTalkRulesUtility.Program.ImportPolicies() in C:\data\biztalk-rules-expo
rt-master\SOURCE\MAIN\BizTalkRulesUtility\Program.cs:line 43
   at BizTalkRulesUtility.Program.Main(String[] args) in C:\data\biztalk-rules-e
xport-master\SOURCE\MAIN\BizTalkRulesUtility\Program.cs:line 23

**Comment by jixer** [comment]
Thanks kianting.  I have merged your fork back into this repo, which includes the fix you provided.  Thank you for helping implement that feature (bug fix).

When you get a chance, please sync this repo back to your fork.
